[copy]
files = ["nginx.conf", "php-fpm.conf"]
target = "/app/"

[phases.setup]
nixpkgs = ["nginx", "php", "phpPackages.composer", "nodejs_18"]

[phases.install]
cmds = [
  "ls -l /app",
  "composer install --ignore-platform-reqs",
  "npm ci",
  "cp nginx.conf /app/nginx.conf",
  "cp php-fpm.conf /app/php-fpm.conf",
  "ls -l /app"
]

[phases.build]
cmds = [
  "npm install",
  "npm run build",
  "mkdir -p /app/public/build",
  "cp -r public/build/* /app/public/build/",
  "echo '--- Content of /app/public/build ---'",
  "ls -l /app/public/build",
  "echo '--- Checking for manifest.json ---'",
  "cat /app/public/build/manifest.json || echo 'manifest.json NOT FOUND'"
]


[phases.start]
cmds = [
  "php artisan migrate --force",
  "php artisan config:clear",
  "php artisan cache:clear",
  "php artisan optimize:clear",
  "ls -l /app",               # check if nginx.conf is there
  "cat /app/nginx.conf",     # check its content
  "php-fpm -y /app/php-fpm.conf & sleep 2",
  "nginx -c /app/nginx.conf -g 'daemon off;'"
]

