[copy]
files = ["nginx.conf"]
target = "/app/nginx.conf"

[phases.setup]
nixpkgs = ["nginx", "php", "phpPackages.composer", "nodejs_18"]

[phases.install]
cmds = [
  "composer install --ignore-platform-reqs",
  "npm ci"
]

[phases.build]
cmds = ["npm run build"]

[phases.start]
cmds = [
  "php artisan migrate --force",
  "php artisan config:clear",
  "php artisan cache:clear",
  "php artisan optimize:clear",
  "ls -l /app",               # check if nginx.conf is there
  "cat /app/nginx.conf",     # check its content
  "php-fpm -y /app/php-fpm.conf & sleep 2",
  "nginx -c /app/nginx.conf -g 'daemon off;'"
]

