[ cors ]
  enabled = true
  allowed_origins = ["https://blog.joniputkinen.com"]
  allowed_methods = ["GET"]
  allowed_headers = ["Content-Type"]
  max_age = 3600

[tasks]
  build = "npm run railway-build"