name: Database Backup

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:     # Allow manual trigger

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger database backup
        run: |
          curl -X POST "https://blog-app-production-16c2.up.railway.app/backup-database.php?token=${{ secrets.ADMIN_SETUP_TOKEN }}"
      
      - name: Check backup status
        if: ${{ always() }}
        run: |
          echo "Backup job completed with status: ${{ job.status }}"
